// Autogenerated from Pigeon (v22.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum DownloadStatus {
  downloading,
  paused,
  finished,
  failed,
  queued,
  removing,
}

class DownloadConfig {
  DownloadConfig({
    required this.url,
    required this.mimeType,
    required this.title,
    required this.audioTrackIds,
    required this.videoTrackIds,
    required this.additionalData,
  });

  String url;

  String mimeType;

  String title;

  List<String?> audioTrackIds;

  List<String?> videoTrackIds;

  Map<String?, String?> additionalData;

  Object encode() {
    return <Object?>[
      url,
      mimeType,
      title,
      audioTrackIds,
      videoTrackIds,
      additionalData,
    ];
  }

  static DownloadConfig decode(Object result) {
    result as List<Object?>;
    return DownloadConfig(
      url: result[0]! as String,
      mimeType: result[1]! as String,
      title: result[2]! as String,
      audioTrackIds: (result[3] as List<Object?>?)!.cast<String?>(),
      videoTrackIds: (result[4] as List<Object?>?)!.cast<String?>(),
      additionalData: (result[5] as Map<Object?, Object?>?)!.cast<String?, String?>(),
    );
  }
}

class Download {
  Download({
    required this.key,
    required this.config,
    this.offlineUrl,
    required this.fractionDownloaded,
    required this.status,
    this.error,
  });

  String key;

  DownloadConfig config;

  String? offlineUrl;

  double fractionDownloaded;

  DownloadStatus status;

  String? error;

  Object encode() {
    return <Object?>[
      key,
      config,
      offlineUrl,
      fractionDownloaded,
      status,
      error,
    ];
  }

  static Download decode(Object result) {
    result as List<Object?>;
    return Download(
      key: result[0]! as String,
      config: result[1]! as DownloadConfig,
      offlineUrl: result[2] as String?,
      fractionDownloaded: result[3]! as double,
      status: result[4]! as DownloadStatus,
      error: result[5] as String?,
    );
  }
}

class DownloadFailedEvent {
  DownloadFailedEvent({
    required this.key,
    this.error,
  });

  String key;

  String? error;

  Object encode() {
    return <Object?>[
      key,
      error,
    ];
  }

  static DownloadFailedEvent decode(Object result) {
    result as List<Object?>;
    return DownloadFailedEvent(
      key: result[0]! as String,
      error: result[1] as String?,
    );
  }
}

class DownloadRemovedEvent {
  DownloadRemovedEvent({
    required this.key,
  });

  String key;

  Object encode() {
    return <Object?>[
      key,
    ];
  }

  static DownloadRemovedEvent decode(Object result) {
    result as List<Object?>;
    return DownloadRemovedEvent(
      key: result[0]! as String,
    );
  }
}

class DownloadChangedEvent {
  DownloadChangedEvent({
    required this.download,
  });

  Download download;

  Object encode() {
    return <Object?>[
      download,
    ];
  }

  static DownloadChangedEvent decode(Object result) {
    result as List<Object?>;
    return DownloadChangedEvent(
      download: result[0]! as Download,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is DownloadStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is DownloadConfig) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is Download) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is DownloadFailedEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is DownloadRemovedEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is DownloadChangedEvent) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DownloadStatus.values[value];
      case 130: 
        return DownloadConfig.decode(readValue(buffer)!);
      case 131: 
        return Download.decode(readValue(buffer)!);
      case 132: 
        return DownloadFailedEvent.decode(readValue(buffer)!);
      case 133: 
        return DownloadRemovedEvent.decode(readValue(buffer)!);
      case 134: 
        return DownloadChangedEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// An API called by the native side to notify about chromecast changes
class DownloaderPigeon {
  /// Constructor for [DownloaderPigeon].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DownloaderPigeon({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<Download> startDownload(DownloadConfig downloadConfig) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bccm_player.DownloaderPigeon.startDownload$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[downloadConfig]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Download?)!;
    }
  }

  Future<double> getDownloadStatus(String downloadKey) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bccm_player.DownloaderPigeon.getDownloadStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[downloadKey]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as double?)!;
    }
  }

  Future<List<Download?>> getDownloads() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bccm_player.DownloaderPigeon.getDownloads$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<Download?>();
    }
  }

  Future<Download?> getDownload(String downloadKey) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bccm_player.DownloaderPigeon.getDownload$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[downloadKey]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as Download?);
    }
  }

  Future<void> removeDownload(String downloadKey) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bccm_player.DownloaderPigeon.removeDownload$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[downloadKey]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Returns free space in bytes
  Future<double> getFreeDiskSpace() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bccm_player.DownloaderPigeon.getFreeDiskSpace$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as double?)!;
    }
  }
}

abstract class DownloaderListenerPigeon {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onDownloadStatusChanged(DownloadChangedEvent event);

  void onDownloadRemoved(DownloadRemovedEvent event);

  void onDownloadFailed(DownloadFailedEvent event);

  static void setUp(DownloaderListenerPigeon? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadStatusChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadStatusChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DownloadChangedEvent? arg_event = (args[0] as DownloadChangedEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadStatusChanged was null, expected non-null DownloadChangedEvent.');
          try {
            api.onDownloadStatusChanged(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadRemoved$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadRemoved was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DownloadRemovedEvent? arg_event = (args[0] as DownloadRemovedEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadRemoved was null, expected non-null DownloadRemovedEvent.');
          try {
            api.onDownloadRemoved(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadFailed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadFailed was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DownloadFailedEvent? arg_event = (args[0] as DownloadFailedEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadFailed was null, expected non-null DownloadFailedEvent.');
          try {
            api.onDownloadFailed(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
