// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum DownloaderApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum DownloadStatus: Int, CaseIterable {
  case downloading = 0
  case paused = 1
  case finished = 2
  case failed = 3
  case queued = 4
  case removing = 5
}

/// Generated class from Pigeon that represents data sent in messages.
struct DownloadConfig: Hashable, CustomStringConvertible {
  var url: String
  var mimeType: String
  var title: String
  var audioTrackIds: [String?]
  var videoTrackIds: [String?]
  var additionalData: [String?: String?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DownloadConfig? {
    let url = pigeonVar_list[0] as! String
    let mimeType = pigeonVar_list[1] as! String
    let title = pigeonVar_list[2] as! String
    let audioTrackIds = pigeonVar_list[3] as! [String?]
    let videoTrackIds = pigeonVar_list[4] as! [String?]
    let additionalData = pigeonVar_list[5] as! [String?: String?]

    return DownloadConfig(
      url: url,
      mimeType: mimeType,
      title: title,
      audioTrackIds: audioTrackIds,
      videoTrackIds: videoTrackIds,
      additionalData: additionalData
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      mimeType,
      title,
      audioTrackIds,
      videoTrackIds,
      additionalData,
    ]
  }
  static func == (lhs: DownloadConfig, rhs: DownloadConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DownloaderApiPigeonInternal.deepEquals(lhs.url, rhs.url) && DownloaderApiPigeonInternal.deepEquals(lhs.mimeType, rhs.mimeType) && DownloaderApiPigeonInternal.deepEquals(lhs.title, rhs.title) && DownloaderApiPigeonInternal.deepEquals(lhs.audioTrackIds, rhs.audioTrackIds) && DownloaderApiPigeonInternal.deepEquals(lhs.videoTrackIds, rhs.videoTrackIds) && DownloaderApiPigeonInternal.deepEquals(lhs.additionalData, rhs.additionalData)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DownloadConfig")
    DownloaderApiPigeonInternal.deepHash(value: url, hasher: &hasher)
    DownloaderApiPigeonInternal.deepHash(value: mimeType, hasher: &hasher)
    DownloaderApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    DownloaderApiPigeonInternal.deepHash(value: audioTrackIds, hasher: &hasher)
    DownloaderApiPigeonInternal.deepHash(value: videoTrackIds, hasher: &hasher)
    DownloaderApiPigeonInternal.deepHash(value: additionalData, hasher: &hasher)
  }

  public var description: String {
    return "DownloadConfig(url: \(String(describing: url)), mimeType: \(String(describing: mimeType)), title: \(String(describing: title)), audioTrackIds: \(String(describing: audioTrackIds)), videoTrackIds: \(String(describing: videoTrackIds)), additionalData: \(String(describing: additionalData)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Download: Hashable, CustomStringConvertible {
  var key: String
  var config: DownloadConfig
  var offlineUrl: String? = nil
  var fractionDownloaded: Double
  var status: DownloadStatus
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Download? {
    let key = pigeonVar_list[0] as! String
    let config = pigeonVar_list[1] as! DownloadConfig
    let offlineUrl: String? = nilOrValue(pigeonVar_list[2])
    let fractionDownloaded = pigeonVar_list[3] as! Double
    let status = pigeonVar_list[4] as! DownloadStatus
    let error: String? = nilOrValue(pigeonVar_list[5])

    return Download(
      key: key,
      config: config,
      offlineUrl: offlineUrl,
      fractionDownloaded: fractionDownloaded,
      status: status,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      config,
      offlineUrl,
      fractionDownloaded,
      status,
      error,
    ]
  }
  static func == (lhs: Download, rhs: Download) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DownloaderApiPigeonInternal.deepEquals(lhs.key, rhs.key) && DownloaderApiPigeonInternal.deepEquals(lhs.config, rhs.config) && DownloaderApiPigeonInternal.deepEquals(lhs.offlineUrl, rhs.offlineUrl) && DownloaderApiPigeonInternal.deepEquals(lhs.fractionDownloaded, rhs.fractionDownloaded) && DownloaderApiPigeonInternal.deepEquals(lhs.status, rhs.status) && DownloaderApiPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Download")
    DownloaderApiPigeonInternal.deepHash(value: key, hasher: &hasher)
    DownloaderApiPigeonInternal.deepHash(value: config, hasher: &hasher)
    DownloaderApiPigeonInternal.deepHash(value: offlineUrl, hasher: &hasher)
    DownloaderApiPigeonInternal.deepHash(value: fractionDownloaded, hasher: &hasher)
    DownloaderApiPigeonInternal.deepHash(value: status, hasher: &hasher)
    DownloaderApiPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "Download(key: \(String(describing: key)), config: \(String(describing: config)), offlineUrl: \(String(describing: offlineUrl)), fractionDownloaded: \(String(describing: fractionDownloaded)), status: \(String(describing: status)), error: \(String(describing: error)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DownloadFailedEvent: Hashable, CustomStringConvertible {
  var key: String
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DownloadFailedEvent? {
    let key = pigeonVar_list[0] as! String
    let error: String? = nilOrValue(pigeonVar_list[1])

    return DownloadFailedEvent(
      key: key,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      error,
    ]
  }
  static func == (lhs: DownloadFailedEvent, rhs: DownloadFailedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DownloaderApiPigeonInternal.deepEquals(lhs.key, rhs.key) && DownloaderApiPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DownloadFailedEvent")
    DownloaderApiPigeonInternal.deepHash(value: key, hasher: &hasher)
    DownloaderApiPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "DownloadFailedEvent(key: \(String(describing: key)), error: \(String(describing: error)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DownloadRemovedEvent: Hashable, CustomStringConvertible {
  var key: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DownloadRemovedEvent? {
    let key = pigeonVar_list[0] as! String

    return DownloadRemovedEvent(
      key: key
    )
  }
  func toList() -> [Any?] {
    return [
      key
    ]
  }
  static func == (lhs: DownloadRemovedEvent, rhs: DownloadRemovedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DownloaderApiPigeonInternal.deepEquals(lhs.key, rhs.key)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DownloadRemovedEvent")
    DownloaderApiPigeonInternal.deepHash(value: key, hasher: &hasher)
  }

  public var description: String {
    return "DownloadRemovedEvent(key: \(String(describing: key)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DownloadChangedEvent: Hashable, CustomStringConvertible {
  var download: Download


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DownloadChangedEvent? {
    let download = pigeonVar_list[0] as! Download

    return DownloadChangedEvent(
      download: download
    )
  }
  func toList() -> [Any?] {
    return [
      download
    ]
  }
  static func == (lhs: DownloadChangedEvent, rhs: DownloadChangedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DownloaderApiPigeonInternal.deepEquals(lhs.download, rhs.download)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DownloadChangedEvent")
    DownloaderApiPigeonInternal.deepHash(value: download, hasher: &hasher)
  }

  public var description: String {
    return "DownloadChangedEvent(download: \(String(describing: download)))"
  }
}

private class DownloaderApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DownloadStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return DownloadConfig.fromList(self.readValue() as! [Any?])
    case 131:
      return Download.fromList(self.readValue() as! [Any?])
    case 132:
      return DownloadFailedEvent.fromList(self.readValue() as! [Any?])
    case 133:
      return DownloadRemovedEvent.fromList(self.readValue() as! [Any?])
    case 134:
      return DownloadChangedEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DownloaderApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DownloadStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? DownloadConfig {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? Download {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? DownloadFailedEvent {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? DownloadRemovedEvent {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? DownloadChangedEvent {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DownloaderApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DownloaderApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DownloaderApiPigeonCodecWriter(data: data)
  }
}

class DownloaderApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DownloaderApiPigeonCodec(readerWriter: DownloaderApiPigeonCodecReaderWriter())
}


/// An API called by the native side to notify about chromecast changes
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DownloaderPigeon {
  func startDownload(downloadConfig: DownloadConfig) async throws -> Download
  func getDownloadStatus(downloadKey: String) async throws -> Double
  func getDownloads() async throws -> [Download]
  func getDownload(downloadKey: String) async throws -> Download?
  func removeDownload(downloadKey: String) async throws
  /// Returns free space in bytes
  func getFreeDiskSpace() async throws -> Double
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DownloaderPigeonSetup {
  static var codec: FlutterStandardMessageCodec { DownloaderApiPigeonCodec.shared }
  /// Sets up an instance of `DownloaderPigeon` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DownloaderPigeon?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bccm_player.DownloaderPigeon.startDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let downloadConfigArg = args[0] as! DownloadConfig
        Task { @MainActor in
          do {
            let result = try await api.startDownload(downloadConfig: downloadConfigArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startDownloadChannel.setMessageHandler(nil)
    }
    let getDownloadStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bccm_player.DownloaderPigeon.getDownloadStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDownloadStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let downloadKeyArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.getDownloadStatus(downloadKey: downloadKeyArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDownloadStatusChannel.setMessageHandler(nil)
    }
    let getDownloadsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bccm_player.DownloaderPigeon.getDownloads\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDownloadsChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.getDownloads()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDownloadsChannel.setMessageHandler(nil)
    }
    let getDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bccm_player.DownloaderPigeon.getDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let downloadKeyArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.getDownload(downloadKey: downloadKeyArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDownloadChannel.setMessageHandler(nil)
    }
    let removeDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bccm_player.DownloaderPigeon.removeDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let downloadKeyArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.removeDownload(downloadKey: downloadKeyArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeDownloadChannel.setMessageHandler(nil)
    }
    /// Returns free space in bytes
    let getFreeDiskSpaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bccm_player.DownloaderPigeon.getFreeDiskSpace\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFreeDiskSpaceChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.getFreeDiskSpace()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getFreeDiskSpaceChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DownloaderListenerPigeonProtocol {
  func onDownloadStatusChanged(event eventArg: DownloadChangedEvent) async throws
  func onDownloadRemoved(event eventArg: DownloadRemovedEvent) async throws
  func onDownloadFailed(event eventArg: DownloadFailedEvent) async throws
}
class DownloaderListenerPigeon: DownloaderListenerPigeonProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: DownloaderApiPigeonCodec {
    return DownloaderApiPigeonCodec.shared
  }
  func onDownloadStatusChanged(event eventArg: DownloadChangedEvent) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadStatusChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onDownloadRemoved(event eventArg: DownloadRemovedEvent) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadRemoved\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onDownloadFailed(event eventArg: DownloadFailedEvent) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadFailed\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
