// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "DownloaderApi.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface DownloadConfig ()
+ (DownloadConfig *)fromList:(NSArray *)list;
+ (nullable DownloadConfig *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface Download ()
+ (Download *)fromList:(NSArray *)list;
+ (nullable Download *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface DownloadFailedEvent ()
+ (DownloadFailedEvent *)fromList:(NSArray *)list;
+ (nullable DownloadFailedEvent *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface DownloadRemovedEvent ()
+ (DownloadRemovedEvent *)fromList:(NSArray *)list;
+ (nullable DownloadRemovedEvent *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface DownloadChangedEvent ()
+ (DownloadChangedEvent *)fromList:(NSArray *)list;
+ (nullable DownloadChangedEvent *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation DownloadConfig
+ (instancetype)makeWithUrl:(NSString *)url
    mimeType:(NSString *)mimeType
    title:(NSString *)title
    audioTrackIds:(NSArray<NSString *> *)audioTrackIds
    videoTrackIds:(NSArray<NSString *> *)videoTrackIds
    additionalData:(NSDictionary<NSString *, NSString *> *)additionalData {
  DownloadConfig* pigeonResult = [[DownloadConfig alloc] init];
  pigeonResult.url = url;
  pigeonResult.mimeType = mimeType;
  pigeonResult.title = title;
  pigeonResult.audioTrackIds = audioTrackIds;
  pigeonResult.videoTrackIds = videoTrackIds;
  pigeonResult.additionalData = additionalData;
  return pigeonResult;
}
+ (DownloadConfig *)fromList:(NSArray *)list {
  DownloadConfig *pigeonResult = [[DownloadConfig alloc] init];
  pigeonResult.url = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.url != nil, @"");
  pigeonResult.mimeType = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.mimeType != nil, @"");
  pigeonResult.title = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.title != nil, @"");
  pigeonResult.audioTrackIds = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.audioTrackIds != nil, @"");
  pigeonResult.videoTrackIds = GetNullableObjectAtIndex(list, 4);
  NSAssert(pigeonResult.videoTrackIds != nil, @"");
  pigeonResult.additionalData = GetNullableObjectAtIndex(list, 5);
  NSAssert(pigeonResult.additionalData != nil, @"");
  return pigeonResult;
}
+ (nullable DownloadConfig *)nullableFromList:(NSArray *)list {
  return (list) ? [DownloadConfig fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.url ?: [NSNull null]),
    (self.mimeType ?: [NSNull null]),
    (self.title ?: [NSNull null]),
    (self.audioTrackIds ?: [NSNull null]),
    (self.videoTrackIds ?: [NSNull null]),
    (self.additionalData ?: [NSNull null]),
  ];
}
@end

@implementation Download
+ (instancetype)makeWithKey:(NSString *)key
    config:(DownloadConfig *)config
    offlineUrl:(nullable NSString *)offlineUrl
    fractionDownloaded:(NSNumber *)fractionDownloaded
    status:(DownloadStatus)status
    error:(nullable NSString *)error {
  Download* pigeonResult = [[Download alloc] init];
  pigeonResult.key = key;
  pigeonResult.config = config;
  pigeonResult.offlineUrl = offlineUrl;
  pigeonResult.fractionDownloaded = fractionDownloaded;
  pigeonResult.status = status;
  pigeonResult.error = error;
  return pigeonResult;
}
+ (Download *)fromList:(NSArray *)list {
  Download *pigeonResult = [[Download alloc] init];
  pigeonResult.key = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.key != nil, @"");
  pigeonResult.config = [DownloadConfig nullableFromList:(GetNullableObjectAtIndex(list, 1))];
  NSAssert(pigeonResult.config != nil, @"");
  pigeonResult.offlineUrl = GetNullableObjectAtIndex(list, 2);
  pigeonResult.fractionDownloaded = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.fractionDownloaded != nil, @"");
  pigeonResult.status = [GetNullableObjectAtIndex(list, 4) integerValue];
  pigeonResult.error = GetNullableObjectAtIndex(list, 5);
  return pigeonResult;
}
+ (nullable Download *)nullableFromList:(NSArray *)list {
  return (list) ? [Download fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.key ?: [NSNull null]),
    (self.config ? [self.config toList] : [NSNull null]),
    (self.offlineUrl ?: [NSNull null]),
    (self.fractionDownloaded ?: [NSNull null]),
    @(self.status),
    (self.error ?: [NSNull null]),
  ];
}
@end

@implementation DownloadFailedEvent
+ (instancetype)makeWithKey:(NSString *)key
    error:(nullable NSString *)error {
  DownloadFailedEvent* pigeonResult = [[DownloadFailedEvent alloc] init];
  pigeonResult.key = key;
  pigeonResult.error = error;
  return pigeonResult;
}
+ (DownloadFailedEvent *)fromList:(NSArray *)list {
  DownloadFailedEvent *pigeonResult = [[DownloadFailedEvent alloc] init];
  pigeonResult.key = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.key != nil, @"");
  pigeonResult.error = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable DownloadFailedEvent *)nullableFromList:(NSArray *)list {
  return (list) ? [DownloadFailedEvent fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.key ?: [NSNull null]),
    (self.error ?: [NSNull null]),
  ];
}
@end

@implementation DownloadRemovedEvent
+ (instancetype)makeWithKey:(NSString *)key {
  DownloadRemovedEvent* pigeonResult = [[DownloadRemovedEvent alloc] init];
  pigeonResult.key = key;
  return pigeonResult;
}
+ (DownloadRemovedEvent *)fromList:(NSArray *)list {
  DownloadRemovedEvent *pigeonResult = [[DownloadRemovedEvent alloc] init];
  pigeonResult.key = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.key != nil, @"");
  return pigeonResult;
}
+ (nullable DownloadRemovedEvent *)nullableFromList:(NSArray *)list {
  return (list) ? [DownloadRemovedEvent fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.key ?: [NSNull null]),
  ];
}
@end

@implementation DownloadChangedEvent
+ (instancetype)makeWithDownload:(Download *)download {
  DownloadChangedEvent* pigeonResult = [[DownloadChangedEvent alloc] init];
  pigeonResult.download = download;
  return pigeonResult;
}
+ (DownloadChangedEvent *)fromList:(NSArray *)list {
  DownloadChangedEvent *pigeonResult = [[DownloadChangedEvent alloc] init];
  pigeonResult.download = [Download nullableFromList:(GetNullableObjectAtIndex(list, 0))];
  NSAssert(pigeonResult.download != nil, @"");
  return pigeonResult;
}
+ (nullable DownloadChangedEvent *)nullableFromList:(NSArray *)list {
  return (list) ? [DownloadChangedEvent fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.download ? [self.download toList] : [NSNull null]),
  ];
}
@end

@interface DownloaderPigeonCodecReader : FlutterStandardReader
@end
@implementation DownloaderPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [Download fromList:[self readValue]];
    case 129: 
      return [Download fromList:[self readValue]];
    case 130: 
      return [DownloadConfig fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface DownloaderPigeonCodecWriter : FlutterStandardWriter
@end
@implementation DownloaderPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[Download class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[Download class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[DownloadConfig class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface DownloaderPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation DownloaderPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[DownloaderPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[DownloaderPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *DownloaderPigeonGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    DownloaderPigeonCodecReaderWriter *readerWriter = [[DownloaderPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void DownloaderPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DownloaderPigeon> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.bccm_player.DownloaderPigeon.startDownload"
        binaryMessenger:binaryMessenger
        codec:DownloaderPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startDownload:completion:)], @"DownloaderPigeon api (%@) doesn't respond to @selector(startDownload:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        DownloadConfig *arg_downloadConfig = GetNullableObjectAtIndex(args, 0);
        [api startDownload:arg_downloadConfig completion:^(Download *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.bccm_player.DownloaderPigeon.getDownloadStatus"
        binaryMessenger:binaryMessenger
        codec:DownloaderPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getDownloadStatus:completion:)], @"DownloaderPigeon api (%@) doesn't respond to @selector(getDownloadStatus:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_downloadKey = GetNullableObjectAtIndex(args, 0);
        [api getDownloadStatus:arg_downloadKey completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.bccm_player.DownloaderPigeon.getDownloads"
        binaryMessenger:binaryMessenger
        codec:DownloaderPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getDownloads:)], @"DownloaderPigeon api (%@) doesn't respond to @selector(getDownloads:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getDownloads:^(NSArray<Download *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.bccm_player.DownloaderPigeon.getDownload"
        binaryMessenger:binaryMessenger
        codec:DownloaderPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getDownload:completion:)], @"DownloaderPigeon api (%@) doesn't respond to @selector(getDownload:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_downloadKey = GetNullableObjectAtIndex(args, 0);
        [api getDownload:arg_downloadKey completion:^(Download *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.bccm_player.DownloaderPigeon.removeDownload"
        binaryMessenger:binaryMessenger
        codec:DownloaderPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(removeDownload:completion:)], @"DownloaderPigeon api (%@) doesn't respond to @selector(removeDownload:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_downloadKey = GetNullableObjectAtIndex(args, 0);
        [api removeDownload:arg_downloadKey completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Returns free space in bytes
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.bccm_player.DownloaderPigeon.getFreeDiskSpace"
        binaryMessenger:binaryMessenger
        codec:DownloaderPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getFreeDiskSpace:)], @"DownloaderPigeon api (%@) doesn't respond to @selector(getFreeDiskSpace:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getFreeDiskSpace:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface DownloaderListenerPigeonCodecReader : FlutterStandardReader
@end
@implementation DownloaderListenerPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [Download fromList:[self readValue]];
    case 129: 
      return [DownloadChangedEvent fromList:[self readValue]];
    case 130: 
      return [DownloadConfig fromList:[self readValue]];
    case 131: 
      return [DownloadFailedEvent fromList:[self readValue]];
    case 132: 
      return [DownloadRemovedEvent fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface DownloaderListenerPigeonCodecWriter : FlutterStandardWriter
@end
@implementation DownloaderListenerPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[Download class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[DownloadChangedEvent class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[DownloadConfig class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[DownloadFailedEvent class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[DownloadRemovedEvent class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface DownloaderListenerPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation DownloaderListenerPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[DownloaderListenerPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[DownloaderListenerPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *DownloaderListenerPigeonGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    DownloaderListenerPigeonCodecReaderWriter *readerWriter = [[DownloaderListenerPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

@interface DownloaderListenerPigeon ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation DownloaderListenerPigeon

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)onDownloadStatusChanged:(DownloadChangedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadStatusChanged"
      binaryMessenger:self.binaryMessenger
      codec:DownloaderListenerPigeonGetCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onDownloadRemoved:(DownloadRemovedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadRemoved"
      binaryMessenger:self.binaryMessenger
      codec:DownloaderListenerPigeonGetCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onDownloadFailed:(DownloadFailedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadFailed"
      binaryMessenger:self.binaryMessenger
      codec:DownloaderListenerPigeonGetCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
@end

