// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "PlaybackPlatformApi.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@implementation BufferModeBox
- (instancetype)initWithValue:(BufferMode)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation RepeatModeBox
- (instancetype)initWithValue:(RepeatMode)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation PlaybackStateBox
- (instancetype)initWithValue:(PlaybackState)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation CastConnectionStateBox
- (instancetype)initWithValue:(CastConnectionState)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation TrackTypeBox
- (instancetype)initWithValue:(TrackType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@interface NpawConfig ()
+ (NpawConfig *)fromList:(NSArray<id> *)list;
+ (nullable NpawConfig *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface AppConfig ()
+ (AppConfig *)fromList:(NSArray<id> *)list;
+ (nullable AppConfig *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface MediaItem ()
+ (MediaItem *)fromList:(NSArray<id> *)list;
+ (nullable MediaItem *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface MediaMetadata ()
+ (MediaMetadata *)fromList:(NSArray<id> *)list;
+ (nullable MediaMetadata *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface MediaQueue ()
+ (MediaQueue *)fromList:(NSArray<id> *)list;
+ (nullable MediaQueue *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PlayerStateSnapshot ()
+ (PlayerStateSnapshot *)fromList:(NSArray<id> *)list;
+ (nullable PlayerStateSnapshot *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PlayerError ()
+ (PlayerError *)fromList:(NSArray<id> *)list;
+ (nullable PlayerError *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface VideoSize ()
+ (VideoSize *)fromList:(NSArray<id> *)list;
+ (nullable VideoSize *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface ChromecastState ()
+ (ChromecastState *)fromList:(NSArray<id> *)list;
+ (nullable ChromecastState *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface MediaInfo ()
+ (MediaInfo *)fromList:(NSArray<id> *)list;
+ (nullable MediaInfo *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PlayerTracksSnapshot ()
+ (PlayerTracksSnapshot *)fromList:(NSArray<id> *)list;
+ (nullable PlayerTracksSnapshot *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface Track ()
+ (Track *)fromList:(NSArray<id> *)list;
+ (nullable Track *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface QueueChangedEvent ()
+ (QueueChangedEvent *)fromList:(NSArray<id> *)list;
+ (nullable QueueChangedEvent *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PrimaryPlayerChangedEvent ()
+ (PrimaryPlayerChangedEvent *)fromList:(NSArray<id> *)list;
+ (nullable PrimaryPlayerChangedEvent *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PlayerStateUpdateEvent ()
+ (PlayerStateUpdateEvent *)fromList:(NSArray<id> *)list;
+ (nullable PlayerStateUpdateEvent *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PositionDiscontinuityEvent ()
+ (PositionDiscontinuityEvent *)fromList:(NSArray<id> *)list;
+ (nullable PositionDiscontinuityEvent *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PlaybackStateChangedEvent ()
+ (PlaybackStateChangedEvent *)fromList:(NSArray<id> *)list;
+ (nullable PlaybackStateChangedEvent *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PlaybackEndedEvent ()
+ (PlaybackEndedEvent *)fromList:(NSArray<id> *)list;
+ (nullable PlaybackEndedEvent *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PictureInPictureModeChangedEvent ()
+ (PictureInPictureModeChangedEvent *)fromList:(NSArray<id> *)list;
+ (nullable PictureInPictureModeChangedEvent *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface MediaItemTransitionEvent ()
+ (MediaItemTransitionEvent *)fromList:(NSArray<id> *)list;
+ (nullable MediaItemTransitionEvent *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation NpawConfig
+ (instancetype)makeWithAppName:(nullable NSString *)appName
    appReleaseVersion:(nullable NSString *)appReleaseVersion
    accountCode:(nullable NSString *)accountCode
    deviceIsAnonymous:(nullable NSNumber *)deviceIsAnonymous {
  NpawConfig* pigeonResult = [[NpawConfig alloc] init];
  pigeonResult.appName = appName;
  pigeonResult.appReleaseVersion = appReleaseVersion;
  pigeonResult.accountCode = accountCode;
  pigeonResult.deviceIsAnonymous = deviceIsAnonymous;
  return pigeonResult;
}
+ (NpawConfig *)fromList:(NSArray<id> *)list {
  NpawConfig *pigeonResult = [[NpawConfig alloc] init];
  pigeonResult.appName = GetNullableObjectAtIndex(list, 0);
  pigeonResult.appReleaseVersion = GetNullableObjectAtIndex(list, 1);
  pigeonResult.accountCode = GetNullableObjectAtIndex(list, 2);
  pigeonResult.deviceIsAnonymous = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable NpawConfig *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [NpawConfig fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.appName ?: [NSNull null],
    self.appReleaseVersion ?: [NSNull null],
    self.accountCode ?: [NSNull null],
    self.deviceIsAnonymous ?: [NSNull null],
  ];
}
@end

@implementation AppConfig
+ (instancetype)makeWithAppLanguage:(nullable NSString *)appLanguage
    audioLanguages:(NSArray<NSString *> *)audioLanguages
    subtitleLanguages:(NSArray<NSString *> *)subtitleLanguages
    analyticsId:(nullable NSString *)analyticsId
    sessionId:(nullable NSNumber *)sessionId {
  AppConfig* pigeonResult = [[AppConfig alloc] init];
  pigeonResult.appLanguage = appLanguage;
  pigeonResult.audioLanguages = audioLanguages;
  pigeonResult.subtitleLanguages = subtitleLanguages;
  pigeonResult.analyticsId = analyticsId;
  pigeonResult.sessionId = sessionId;
  return pigeonResult;
}
+ (AppConfig *)fromList:(NSArray<id> *)list {
  AppConfig *pigeonResult = [[AppConfig alloc] init];
  pigeonResult.appLanguage = GetNullableObjectAtIndex(list, 0);
  pigeonResult.audioLanguages = GetNullableObjectAtIndex(list, 1);
  pigeonResult.subtitleLanguages = GetNullableObjectAtIndex(list, 2);
  pigeonResult.analyticsId = GetNullableObjectAtIndex(list, 3);
  pigeonResult.sessionId = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable AppConfig *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [AppConfig fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.appLanguage ?: [NSNull null],
    self.audioLanguages ?: [NSNull null],
    self.subtitleLanguages ?: [NSNull null],
    self.analyticsId ?: [NSNull null],
    self.sessionId ?: [NSNull null],
  ];
}
@end

@implementation MediaItem
+ (instancetype)makeWithId:(nullable NSString *)id
    url:(nullable NSString *)url
    mimeType:(nullable NSString *)mimeType
    metadata:(nullable MediaMetadata *)metadata
    isLive:(nullable NSNumber *)isLive
    isOffline:(nullable NSNumber *)isOffline
    playbackStartPositionMs:(nullable NSNumber *)playbackStartPositionMs
    lastKnownAudioLanguage:(nullable NSString *)lastKnownAudioLanguage
    lastKnownSubtitleLanguage:(nullable NSString *)lastKnownSubtitleLanguage {
  MediaItem* pigeonResult = [[MediaItem alloc] init];
  pigeonResult.id = id;
  pigeonResult.url = url;
  pigeonResult.mimeType = mimeType;
  pigeonResult.metadata = metadata;
  pigeonResult.isLive = isLive;
  pigeonResult.isOffline = isOffline;
  pigeonResult.playbackStartPositionMs = playbackStartPositionMs;
  pigeonResult.lastKnownAudioLanguage = lastKnownAudioLanguage;
  pigeonResult.lastKnownSubtitleLanguage = lastKnownSubtitleLanguage;
  return pigeonResult;
}
+ (MediaItem *)fromList:(NSArray<id> *)list {
  MediaItem *pigeonResult = [[MediaItem alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  pigeonResult.url = GetNullableObjectAtIndex(list, 1);
  pigeonResult.mimeType = GetNullableObjectAtIndex(list, 2);
  pigeonResult.metadata = GetNullableObjectAtIndex(list, 3);
  pigeonResult.isLive = GetNullableObjectAtIndex(list, 4);
  pigeonResult.isOffline = GetNullableObjectAtIndex(list, 5);
  pigeonResult.playbackStartPositionMs = GetNullableObjectAtIndex(list, 6);
  pigeonResult.lastKnownAudioLanguage = GetNullableObjectAtIndex(list, 7);
  pigeonResult.lastKnownSubtitleLanguage = GetNullableObjectAtIndex(list, 8);
  return pigeonResult;
}
+ (nullable MediaItem *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [MediaItem fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.id ?: [NSNull null],
    self.url ?: [NSNull null],
    self.mimeType ?: [NSNull null],
    self.metadata ?: [NSNull null],
    self.isLive ?: [NSNull null],
    self.isOffline ?: [NSNull null],
    self.playbackStartPositionMs ?: [NSNull null],
    self.lastKnownAudioLanguage ?: [NSNull null],
    self.lastKnownSubtitleLanguage ?: [NSNull null],
  ];
}
@end

@implementation MediaMetadata
+ (instancetype)makeWithArtworkUri:(nullable NSString *)artworkUri
    title:(nullable NSString *)title
    artist:(nullable NSString *)artist
    durationMs:(nullable NSNumber *)durationMs
    extras:(nullable NSDictionary<NSString *, NSString *> *)extras {
  MediaMetadata* pigeonResult = [[MediaMetadata alloc] init];
  pigeonResult.artworkUri = artworkUri;
  pigeonResult.title = title;
  pigeonResult.artist = artist;
  pigeonResult.durationMs = durationMs;
  pigeonResult.extras = extras;
  return pigeonResult;
}
+ (MediaMetadata *)fromList:(NSArray<id> *)list {
  MediaMetadata *pigeonResult = [[MediaMetadata alloc] init];
  pigeonResult.artworkUri = GetNullableObjectAtIndex(list, 0);
  pigeonResult.title = GetNullableObjectAtIndex(list, 1);
  pigeonResult.artist = GetNullableObjectAtIndex(list, 2);
  pigeonResult.durationMs = GetNullableObjectAtIndex(list, 3);
  pigeonResult.extras = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable MediaMetadata *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [MediaMetadata fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.artworkUri ?: [NSNull null],
    self.title ?: [NSNull null],
    self.artist ?: [NSNull null],
    self.durationMs ?: [NSNull null],
    self.extras ?: [NSNull null],
  ];
}
@end

@implementation MediaQueue
+ (instancetype)makeWithQueue:(NSArray<MediaItem *> *)queue
    nextUp:(NSArray<MediaItem *> *)nextUp
    shuffleEnabled:(BOOL )shuffleEnabled {
  MediaQueue* pigeonResult = [[MediaQueue alloc] init];
  pigeonResult.queue = queue;
  pigeonResult.nextUp = nextUp;
  pigeonResult.shuffleEnabled = shuffleEnabled;
  return pigeonResult;
}
+ (MediaQueue *)fromList:(NSArray<id> *)list {
  MediaQueue *pigeonResult = [[MediaQueue alloc] init];
  pigeonResult.queue = GetNullableObjectAtIndex(list, 0);
  pigeonResult.nextUp = GetNullableObjectAtIndex(list, 1);
  pigeonResult.shuffleEnabled = [GetNullableObjectAtIndex(list, 2) boolValue];
  return pigeonResult;
}
+ (nullable MediaQueue *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [MediaQueue fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.queue ?: [NSNull null],
    self.nextUp ?: [NSNull null],
    @(self.shuffleEnabled),
  ];
}
@end

@implementation PlayerStateSnapshot
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    playbackState:(PlaybackState)playbackState
    isBuffering:(BOOL )isBuffering
    isFullscreen:(BOOL )isFullscreen
    playbackSpeed:(double )playbackSpeed
    videoSize:(nullable VideoSize *)videoSize
    currentMediaItem:(nullable MediaItem *)currentMediaItem
    playbackPositionMs:(nullable NSNumber *)playbackPositionMs
    textureId:(nullable NSNumber *)textureId
    volume:(nullable NSNumber *)volume
    error:(nullable PlayerError *)error {
  PlayerStateSnapshot* pigeonResult = [[PlayerStateSnapshot alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.playbackState = playbackState;
  pigeonResult.isBuffering = isBuffering;
  pigeonResult.isFullscreen = isFullscreen;
  pigeonResult.playbackSpeed = playbackSpeed;
  pigeonResult.videoSize = videoSize;
  pigeonResult.currentMediaItem = currentMediaItem;
  pigeonResult.playbackPositionMs = playbackPositionMs;
  pigeonResult.textureId = textureId;
  pigeonResult.volume = volume;
  pigeonResult.error = error;
  return pigeonResult;
}
+ (PlayerStateSnapshot *)fromList:(NSArray<id> *)list {
  PlayerStateSnapshot *pigeonResult = [[PlayerStateSnapshot alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  PlaybackStateBox *boxedPlaybackState = GetNullableObjectAtIndex(list, 1);
  pigeonResult.playbackState = boxedPlaybackState.value;
  pigeonResult.isBuffering = [GetNullableObjectAtIndex(list, 2) boolValue];
  pigeonResult.isFullscreen = [GetNullableObjectAtIndex(list, 3) boolValue];
  pigeonResult.playbackSpeed = [GetNullableObjectAtIndex(list, 4) doubleValue];
  pigeonResult.videoSize = GetNullableObjectAtIndex(list, 5);
  pigeonResult.currentMediaItem = GetNullableObjectAtIndex(list, 6);
  pigeonResult.playbackPositionMs = GetNullableObjectAtIndex(list, 7);
  pigeonResult.textureId = GetNullableObjectAtIndex(list, 8);
  pigeonResult.volume = GetNullableObjectAtIndex(list, 9);
  pigeonResult.error = GetNullableObjectAtIndex(list, 10);
  return pigeonResult;
}
+ (nullable PlayerStateSnapshot *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PlayerStateSnapshot fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.playerId ?: [NSNull null],
    [[PlaybackStateBox alloc] initWithValue:self.playbackState],
    @(self.isBuffering),
    @(self.isFullscreen),
    @(self.playbackSpeed),
    self.videoSize ?: [NSNull null],
    self.currentMediaItem ?: [NSNull null],
    self.playbackPositionMs ?: [NSNull null],
    self.textureId ?: [NSNull null],
    self.volume ?: [NSNull null],
    self.error ?: [NSNull null],
  ];
}
@end

@implementation PlayerError
+ (instancetype)makeWithCode:(nullable NSString *)code
    message:(nullable NSString *)message {
  PlayerError* pigeonResult = [[PlayerError alloc] init];
  pigeonResult.code = code;
  pigeonResult.message = message;
  return pigeonResult;
}
+ (PlayerError *)fromList:(NSArray<id> *)list {
  PlayerError *pigeonResult = [[PlayerError alloc] init];
  pigeonResult.code = GetNullableObjectAtIndex(list, 0);
  pigeonResult.message = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable PlayerError *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PlayerError fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.code ?: [NSNull null],
    self.message ?: [NSNull null],
  ];
}
@end

@implementation VideoSize
+ (instancetype)makeWithWidth:(NSInteger )width
    height:(NSInteger )height {
  VideoSize* pigeonResult = [[VideoSize alloc] init];
  pigeonResult.width = width;
  pigeonResult.height = height;
  return pigeonResult;
}
+ (VideoSize *)fromList:(NSArray<id> *)list {
  VideoSize *pigeonResult = [[VideoSize alloc] init];
  pigeonResult.width = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.height = [GetNullableObjectAtIndex(list, 1) integerValue];
  return pigeonResult;
}
+ (nullable VideoSize *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [VideoSize fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.width),
    @(self.height),
  ];
}
@end

@implementation ChromecastState
+ (instancetype)makeWithConnectionState:(CastConnectionState)connectionState
    mediaItem:(nullable MediaItem *)mediaItem {
  ChromecastState* pigeonResult = [[ChromecastState alloc] init];
  pigeonResult.connectionState = connectionState;
  pigeonResult.mediaItem = mediaItem;
  return pigeonResult;
}
+ (ChromecastState *)fromList:(NSArray<id> *)list {
  ChromecastState *pigeonResult = [[ChromecastState alloc] init];
  CastConnectionStateBox *boxedCastConnectionState = GetNullableObjectAtIndex(list, 0);
  pigeonResult.connectionState = boxedCastConnectionState.value;
  pigeonResult.mediaItem = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable ChromecastState *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [ChromecastState fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    [[CastConnectionStateBox alloc] initWithValue:self.connectionState],
    self.mediaItem ?: [NSNull null],
  ];
}
@end

@implementation MediaInfo
+ (instancetype)makeWithAudioTracks:(NSArray<Track *> *)audioTracks
    textTracks:(NSArray<Track *> *)textTracks
    videoTracks:(NSArray<Track *> *)videoTracks {
  MediaInfo* pigeonResult = [[MediaInfo alloc] init];
  pigeonResult.audioTracks = audioTracks;
  pigeonResult.textTracks = textTracks;
  pigeonResult.videoTracks = videoTracks;
  return pigeonResult;
}
+ (MediaInfo *)fromList:(NSArray<id> *)list {
  MediaInfo *pigeonResult = [[MediaInfo alloc] init];
  pigeonResult.audioTracks = GetNullableObjectAtIndex(list, 0);
  pigeonResult.textTracks = GetNullableObjectAtIndex(list, 1);
  pigeonResult.videoTracks = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable MediaInfo *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [MediaInfo fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.audioTracks ?: [NSNull null],
    self.textTracks ?: [NSNull null],
    self.videoTracks ?: [NSNull null],
  ];
}
@end

@implementation PlayerTracksSnapshot
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    audioTracks:(NSArray<Track *> *)audioTracks
    textTracks:(NSArray<Track *> *)textTracks
    videoTracks:(NSArray<Track *> *)videoTracks {
  PlayerTracksSnapshot* pigeonResult = [[PlayerTracksSnapshot alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.audioTracks = audioTracks;
  pigeonResult.textTracks = textTracks;
  pigeonResult.videoTracks = videoTracks;
  return pigeonResult;
}
+ (PlayerTracksSnapshot *)fromList:(NSArray<id> *)list {
  PlayerTracksSnapshot *pigeonResult = [[PlayerTracksSnapshot alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.audioTracks = GetNullableObjectAtIndex(list, 1);
  pigeonResult.textTracks = GetNullableObjectAtIndex(list, 2);
  pigeonResult.videoTracks = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable PlayerTracksSnapshot *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PlayerTracksSnapshot fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.playerId ?: [NSNull null],
    self.audioTracks ?: [NSNull null],
    self.textTracks ?: [NSNull null],
    self.videoTracks ?: [NSNull null],
  ];
}
@end

@implementation Track
+ (instancetype)makeWithId:(NSString *)id
    label:(nullable NSString *)label
    language:(nullable NSString *)language
    frameRate:(nullable NSNumber *)frameRate
    bitrate:(nullable NSNumber *)bitrate
    width:(nullable NSNumber *)width
    height:(nullable NSNumber *)height
    downloaded:(nullable NSNumber *)downloaded
    isSelected:(BOOL )isSelected {
  Track* pigeonResult = [[Track alloc] init];
  pigeonResult.id = id;
  pigeonResult.label = label;
  pigeonResult.language = language;
  pigeonResult.frameRate = frameRate;
  pigeonResult.bitrate = bitrate;
  pigeonResult.width = width;
  pigeonResult.height = height;
  pigeonResult.downloaded = downloaded;
  pigeonResult.isSelected = isSelected;
  return pigeonResult;
}
+ (Track *)fromList:(NSArray<id> *)list {
  Track *pigeonResult = [[Track alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  pigeonResult.label = GetNullableObjectAtIndex(list, 1);
  pigeonResult.language = GetNullableObjectAtIndex(list, 2);
  pigeonResult.frameRate = GetNullableObjectAtIndex(list, 3);
  pigeonResult.bitrate = GetNullableObjectAtIndex(list, 4);
  pigeonResult.width = GetNullableObjectAtIndex(list, 5);
  pigeonResult.height = GetNullableObjectAtIndex(list, 6);
  pigeonResult.downloaded = GetNullableObjectAtIndex(list, 7);
  pigeonResult.isSelected = [GetNullableObjectAtIndex(list, 8) boolValue];
  return pigeonResult;
}
+ (nullable Track *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [Track fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.id ?: [NSNull null],
    self.label ?: [NSNull null],
    self.language ?: [NSNull null],
    self.frameRate ?: [NSNull null],
    self.bitrate ?: [NSNull null],
    self.width ?: [NSNull null],
    self.height ?: [NSNull null],
    self.downloaded ?: [NSNull null],
    @(self.isSelected),
  ];
}
@end

@implementation QueueChangedEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    queue:(nullable MediaQueue *)queue {
  QueueChangedEvent* pigeonResult = [[QueueChangedEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.queue = queue;
  return pigeonResult;
}
+ (QueueChangedEvent *)fromList:(NSArray<id> *)list {
  QueueChangedEvent *pigeonResult = [[QueueChangedEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.queue = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable QueueChangedEvent *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [QueueChangedEvent fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.playerId ?: [NSNull null],
    self.queue ?: [NSNull null],
  ];
}
@end

@implementation PrimaryPlayerChangedEvent
+ (instancetype)makeWithPlayerId:(nullable NSString *)playerId {
  PrimaryPlayerChangedEvent* pigeonResult = [[PrimaryPlayerChangedEvent alloc] init];
  pigeonResult.playerId = playerId;
  return pigeonResult;
}
+ (PrimaryPlayerChangedEvent *)fromList:(NSArray<id> *)list {
  PrimaryPlayerChangedEvent *pigeonResult = [[PrimaryPlayerChangedEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable PrimaryPlayerChangedEvent *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PrimaryPlayerChangedEvent fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.playerId ?: [NSNull null],
  ];
}
@end

@implementation PlayerStateUpdateEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    snapshot:(PlayerStateSnapshot *)snapshot {
  PlayerStateUpdateEvent* pigeonResult = [[PlayerStateUpdateEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.snapshot = snapshot;
  return pigeonResult;
}
+ (PlayerStateUpdateEvent *)fromList:(NSArray<id> *)list {
  PlayerStateUpdateEvent *pigeonResult = [[PlayerStateUpdateEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.snapshot = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable PlayerStateUpdateEvent *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PlayerStateUpdateEvent fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.playerId ?: [NSNull null],
    self.snapshot ?: [NSNull null],
  ];
}
@end

@implementation PositionDiscontinuityEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    playbackPositionMs:(nullable NSNumber *)playbackPositionMs {
  PositionDiscontinuityEvent* pigeonResult = [[PositionDiscontinuityEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.playbackPositionMs = playbackPositionMs;
  return pigeonResult;
}
+ (PositionDiscontinuityEvent *)fromList:(NSArray<id> *)list {
  PositionDiscontinuityEvent *pigeonResult = [[PositionDiscontinuityEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.playbackPositionMs = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable PositionDiscontinuityEvent *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PositionDiscontinuityEvent fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.playerId ?: [NSNull null],
    self.playbackPositionMs ?: [NSNull null],
  ];
}
@end

@implementation PlaybackStateChangedEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    playbackState:(PlaybackState)playbackState
    isBuffering:(BOOL )isBuffering {
  PlaybackStateChangedEvent* pigeonResult = [[PlaybackStateChangedEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.playbackState = playbackState;
  pigeonResult.isBuffering = isBuffering;
  return pigeonResult;
}
+ (PlaybackStateChangedEvent *)fromList:(NSArray<id> *)list {
  PlaybackStateChangedEvent *pigeonResult = [[PlaybackStateChangedEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  PlaybackStateBox *boxedPlaybackState = GetNullableObjectAtIndex(list, 1);
  pigeonResult.playbackState = boxedPlaybackState.value;
  pigeonResult.isBuffering = [GetNullableObjectAtIndex(list, 2) boolValue];
  return pigeonResult;
}
+ (nullable PlaybackStateChangedEvent *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PlaybackStateChangedEvent fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.playerId ?: [NSNull null],
    [[PlaybackStateBox alloc] initWithValue:self.playbackState],
    @(self.isBuffering),
  ];
}
@end

@implementation PlaybackEndedEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    mediaItem:(nullable MediaItem *)mediaItem {
  PlaybackEndedEvent* pigeonResult = [[PlaybackEndedEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.mediaItem = mediaItem;
  return pigeonResult;
}
+ (PlaybackEndedEvent *)fromList:(NSArray<id> *)list {
  PlaybackEndedEvent *pigeonResult = [[PlaybackEndedEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.mediaItem = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable PlaybackEndedEvent *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PlaybackEndedEvent fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.playerId ?: [NSNull null],
    self.mediaItem ?: [NSNull null],
  ];
}
@end

@implementation PictureInPictureModeChangedEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    isInPipMode:(BOOL )isInPipMode {
  PictureInPictureModeChangedEvent* pigeonResult = [[PictureInPictureModeChangedEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.isInPipMode = isInPipMode;
  return pigeonResult;
}
+ (PictureInPictureModeChangedEvent *)fromList:(NSArray<id> *)list {
  PictureInPictureModeChangedEvent *pigeonResult = [[PictureInPictureModeChangedEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.isInPipMode = [GetNullableObjectAtIndex(list, 1) boolValue];
  return pigeonResult;
}
+ (nullable PictureInPictureModeChangedEvent *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PictureInPictureModeChangedEvent fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.playerId ?: [NSNull null],
    @(self.isInPipMode),
  ];
}
@end

@implementation MediaItemTransitionEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    mediaItem:(nullable MediaItem *)mediaItem {
  MediaItemTransitionEvent* pigeonResult = [[MediaItemTransitionEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.mediaItem = mediaItem;
  return pigeonResult;
}
+ (MediaItemTransitionEvent *)fromList:(NSArray<id> *)list {
  MediaItemTransitionEvent *pigeonResult = [[MediaItemTransitionEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.mediaItem = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable MediaItemTransitionEvent *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [MediaItemTransitionEvent fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.playerId ?: [NSNull null],
    self.mediaItem ?: [NSNull null],
  ];
}
@end

@interface nullPlaybackPlatformApiPigeonCodecReader : FlutterStandardReader
@end
@implementation nullPlaybackPlatformApiPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[BufferModeBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 130: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[RepeatModeBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 131: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[PlaybackStateBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 132: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[CastConnectionStateBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 133: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[TrackTypeBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 134: 
      return [NpawConfig fromList:[self readValue]];
    case 135: 
      return [AppConfig fromList:[self readValue]];
    case 136: 
      return [MediaItem fromList:[self readValue]];
    case 137: 
      return [MediaMetadata fromList:[self readValue]];
    case 138: 
      return [MediaQueue fromList:[self readValue]];
    case 139: 
      return [PlayerStateSnapshot fromList:[self readValue]];
    case 140: 
      return [PlayerError fromList:[self readValue]];
    case 141: 
      return [VideoSize fromList:[self readValue]];
    case 142: 
      return [ChromecastState fromList:[self readValue]];
    case 143: 
      return [MediaInfo fromList:[self readValue]];
    case 144: 
      return [PlayerTracksSnapshot fromList:[self readValue]];
    case 145: 
      return [Track fromList:[self readValue]];
    case 146: 
      return [QueueChangedEvent fromList:[self readValue]];
    case 147: 
      return [PrimaryPlayerChangedEvent fromList:[self readValue]];
    case 148: 
      return [PlayerStateUpdateEvent fromList:[self readValue]];
    case 149: 
      return [PositionDiscontinuityEvent fromList:[self readValue]];
    case 150: 
      return [PlaybackStateChangedEvent fromList:[self readValue]];
    case 151: 
      return [PlaybackEndedEvent fromList:[self readValue]];
    case 152: 
      return [PictureInPictureModeChangedEvent fromList:[self readValue]];
    case 153: 
      return [MediaItemTransitionEvent fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullPlaybackPlatformApiPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullPlaybackPlatformApiPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[BufferModeBox class]]) {
    BufferModeBox *box = (BufferModeBox *)value;
    [self writeByte:129];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[RepeatModeBox class]]) {
    RepeatModeBox *box = (RepeatModeBox *)value;
    [self writeByte:130];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[PlaybackStateBox class]]) {
    PlaybackStateBox *box = (PlaybackStateBox *)value;
    [self writeByte:131];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[CastConnectionStateBox class]]) {
    CastConnectionStateBox *box = (CastConnectionStateBox *)value;
    [self writeByte:132];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[TrackTypeBox class]]) {
    TrackTypeBox *box = (TrackTypeBox *)value;
    [self writeByte:133];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[NpawConfig class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[AppConfig class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MediaItem class]]) {
    [self writeByte:136];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MediaMetadata class]]) {
    [self writeByte:137];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MediaQueue class]]) {
    [self writeByte:138];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlayerStateSnapshot class]]) {
    [self writeByte:139];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlayerError class]]) {
    [self writeByte:140];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[VideoSize class]]) {
    [self writeByte:141];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ChromecastState class]]) {
    [self writeByte:142];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MediaInfo class]]) {
    [self writeByte:143];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlayerTracksSnapshot class]]) {
    [self writeByte:144];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[Track class]]) {
    [self writeByte:145];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[QueueChangedEvent class]]) {
    [self writeByte:146];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PrimaryPlayerChangedEvent class]]) {
    [self writeByte:147];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlayerStateUpdateEvent class]]) {
    [self writeByte:148];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PositionDiscontinuityEvent class]]) {
    [self writeByte:149];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlaybackStateChangedEvent class]]) {
    [self writeByte:150];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlaybackEndedEvent class]]) {
    [self writeByte:151];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PictureInPictureModeChangedEvent class]]) {
    [self writeByte:152];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MediaItemTransitionEvent class]]) {
    [self writeByte:153];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface nullPlaybackPlatformApiPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullPlaybackPlatformApiPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullPlaybackPlatformApiPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullPlaybackPlatformApiPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetPlaybackPlatformApiCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullPlaybackPlatformApiPigeonCodecReaderWriter *readerWriter = [[nullPlaybackPlatformApiPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpPlaybackPlatformPigeon(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PlaybackPlatformPigeon> *api) {
  SetUpPlaybackPlatformPigeonWithSuffix(binaryMessenger, api, @"");
}

void SetUpPlaybackPlatformPigeonWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PlaybackPlatformPigeon> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.attach", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(attachWithCompletion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(attachWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api attachWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.newPlayer", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(newPlayer:disableNpaw:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(newPlayer:disableNpaw:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        BufferModeBox *arg_bufferMode = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_disableNpaw = GetNullableObjectAtIndex(args, 1);
        [api newPlayer:arg_bufferMode disableNpaw:arg_disableNpaw completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.createVideoTexture", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createVideoTexture:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(createVideoTexture:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api createVideoTexture:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.disposeVideoTexture", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disposeVideoTexture:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(disposeVideoTexture:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_textureId = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api disposeVideoTexture:arg_textureId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.switchToVideoTexture", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(switchToVideoTextureForPlayer:textureId:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(switchToVideoTextureForPlayer:textureId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        NSInteger arg_textureId = [GetNullableObjectAtIndex(args, 1) integerValue];
        [api switchToVideoTextureForPlayer:arg_playerId textureId:arg_textureId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.disposePlayer", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disposePlayer:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(disposePlayer:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        [api disposePlayer:arg_playerId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.queueMediaItem", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(queueMediaItem:mediaItem:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(queueMediaItem:mediaItem:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        MediaItem *arg_mediaItem = GetNullableObjectAtIndex(args, 1);
        [api queueMediaItem:arg_playerId mediaItem:arg_mediaItem completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.moveQueueItem", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(moveQueueItem:fromIndex:toIndex:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(moveQueueItem:fromIndex:toIndex:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        NSInteger arg_fromIndex = [GetNullableObjectAtIndex(args, 1) integerValue];
        NSInteger arg_toIndex = [GetNullableObjectAtIndex(args, 2) integerValue];
        [api moveQueueItem:arg_playerId fromIndex:arg_fromIndex toIndex:arg_toIndex completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.removeQueueItem", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(removeQueueItem:id:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(removeQueueItem:id:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        NSString *arg_id = GetNullableObjectAtIndex(args, 1);
        [api removeQueueItem:arg_playerId id:arg_id completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.clearQueue", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(clearQueue:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(clearQueue:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        [api clearQueue:arg_playerId completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setNextUpList", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setNextUpList:items:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setNextUpList:items:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        NSArray<MediaItem *> *arg_items = GetNullableObjectAtIndex(args, 1);
        [api setNextUpList:arg_playerId items:arg_items completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.skipToNext", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(skipToNext:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(skipToNext:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        [api skipToNext:arg_playerId completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.skipToPrevious", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(skipToPrevious:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(skipToPrevious:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        [api skipToPrevious:arg_playerId completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setShuffleEnabled", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setShuffleEnabled:mode:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setShuffleEnabled:mode:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        BOOL arg_enabled = [GetNullableObjectAtIndex(args, 1) boolValue];
        [api setShuffleEnabled:arg_playerId mode:arg_enabled completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setCurrentQueueItem", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setCurrentQueueItem:id:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setCurrentQueueItem:id:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        NSString *arg_id = GetNullableObjectAtIndex(args, 1);
        [api setCurrentQueueItem:arg_playerId id:arg_id completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.getQueue", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getQueue:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(getQueue:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        [api getQueue:arg_playerId completion:^(MediaQueue *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.replaceCurrentMediaItem", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(replaceCurrentMediaItem:mediaItem:playbackPositionFromPrimary:autoplay:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(replaceCurrentMediaItem:mediaItem:playbackPositionFromPrimary:autoplay:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        MediaItem *arg_mediaItem = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_playbackPositionFromPrimary = GetNullableObjectAtIndex(args, 2);
        NSNumber *arg_autoplay = GetNullableObjectAtIndex(args, 3);
        [api replaceCurrentMediaItem:arg_playerId mediaItem:arg_mediaItem playbackPositionFromPrimary:arg_playbackPositionFromPrimary autoplay:arg_autoplay completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setPlayerViewVisibility", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPlayerViewVisibility:visible:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setPlayerViewVisibility:visible:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_viewId = [GetNullableObjectAtIndex(args, 0) integerValue];
        BOOL arg_visible = [GetNullableObjectAtIndex(args, 1) boolValue];
        FlutterError *error;
        [api setPlayerViewVisibility:arg_viewId visible:arg_visible error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setPrimary", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPrimary:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setPrimary:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        [api setPrimary:arg_id completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.play", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(play:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(play:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api play:arg_playerId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.seekTo", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(seek:positionMs:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(seek:positionMs:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        double arg_positionMs = [GetNullableObjectAtIndex(args, 1) doubleValue];
        [api seek:arg_playerId positionMs:arg_positionMs completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.pause", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pause:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(pause:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api pause:arg_playerId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.stop", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stop:reset:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(stop:reset:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        BOOL arg_reset = [GetNullableObjectAtIndex(args, 1) boolValue];
        FlutterError *error;
        [api stop:arg_playerId reset:arg_reset error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setVolume", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setVolume:volume:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setVolume:volume:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        double arg_volume = [GetNullableObjectAtIndex(args, 1) doubleValue];
        [api setVolume:arg_playerId volume:arg_volume completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setRepeatMode", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setRepeatMode:repeatMode:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setRepeatMode:repeatMode:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        RepeatModeBox *boxedRepeatMode = GetNullableObjectAtIndex(args, 1);
        RepeatMode arg_repeatMode = boxedRepeatMode.value;
        [api setRepeatMode:arg_playerId repeatMode:arg_repeatMode completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setSelectedTrack", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setSelectedTrack:type:trackId:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setSelectedTrack:type:trackId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        TrackTypeBox *boxedTrackType = GetNullableObjectAtIndex(args, 1);
        TrackType arg_type = boxedTrackType.value;
        NSString *arg_trackId = GetNullableObjectAtIndex(args, 2);
        [api setSelectedTrack:arg_playerId type:arg_type trackId:arg_trackId completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setPlaybackSpeed", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPlaybackSpeed:speed:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setPlaybackSpeed:speed:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        double arg_speed = [GetNullableObjectAtIndex(args, 1) doubleValue];
        [api setPlaybackSpeed:arg_playerId speed:arg_speed completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.exitFullscreen", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(exitFullscreen:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(exitFullscreen:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api exitFullscreen:arg_playerId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.enterFullscreen", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(enterFullscreen:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(enterFullscreen:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api enterFullscreen:arg_playerId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setMixWithOthers", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setMixWithOthers:mixWithOthers:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setMixWithOthers:mixWithOthers:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        BOOL arg_mixWithOthers = [GetNullableObjectAtIndex(args, 1) boolValue];
        [api setMixWithOthers:arg_playerId mixWithOthers:arg_mixWithOthers completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setNpawConfig", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setNpawConfig:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setNpawConfig:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NpawConfig *arg_config = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setNpawConfig:arg_config error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.setAppConfig", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setAppConfig:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setAppConfig:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        AppConfig *arg_config = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setAppConfig:arg_config error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.getTracks", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getTracks:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(getTracks:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        [api getTracks:arg_playerId completion:^(PlayerTracksSnapshot *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.getPlayerState", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPlayerState:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(getPlayerState:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        [api getPlayerState:arg_playerId completion:^(PlayerStateSnapshot *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.getChromecastState", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getChromecastState:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(getChromecastState:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getChromecastState:^(ChromecastState *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.openExpandedCastController", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(openExpandedCastController:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(openExpandedCastController:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api openExpandedCastController:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.openCastDialog", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(openCastDialog:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(openCastDialog:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api openCastDialog:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.fetchMediaInfo", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fetchMediaInfo:mimeType:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(fetchMediaInfo:mimeType:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_url = GetNullableObjectAtIndex(args, 0);
        NSString *arg_mimeType = GetNullableObjectAtIndex(args, 1);
        [api fetchMediaInfo:arg_url mimeType:arg_mimeType completion:^(MediaInfo *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackPlatformPigeon.getAndroidPerformanceClass", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPlaybackPlatformApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getAndroidPerformanceClassWithCompletion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(getAndroidPerformanceClassWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getAndroidPerformanceClassWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface QueueListenerPigeon ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation QueueListenerPigeon

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)onQueueChanged:(QueueChangedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.QueueListenerPigeon.onQueueChanged", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPlaybackPlatformApiCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

@interface PlaybackListenerPigeon ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation PlaybackListenerPigeon

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)onPrimaryPlayerChanged:(PrimaryPlayerChangedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackListenerPigeon.onPrimaryPlayerChanged", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPlaybackPlatformApiCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onPositionDiscontinuity:(PositionDiscontinuityEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackListenerPigeon.onPositionDiscontinuity", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPlaybackPlatformApiCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onPlayerStateUpdate:(PlayerStateUpdateEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackListenerPigeon.onPlayerStateUpdate", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPlaybackPlatformApiCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onPlaybackStateChanged:(PlaybackStateChangedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackListenerPigeon.onPlaybackStateChanged", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPlaybackPlatformApiCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onPlaybackEnded:(PlaybackEndedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackListenerPigeon.onPlaybackEnded", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPlaybackPlatformApiCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onMediaItemTransition:(MediaItemTransitionEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackListenerPigeon.onMediaItemTransition", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPlaybackPlatformApiCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onPictureInPictureModeChanged:(PictureInPictureModeChangedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackListenerPigeon.onPictureInPictureModeChanged", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPlaybackPlatformApiCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onQueueChanged:(QueueChangedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.bccm_player.PlaybackListenerPigeon.onQueueChanged", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPlaybackPlatformApiCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

